### PR TITLE
feat: add ActionMenu component

### LINKED ISSUE #73: Component: ActionMenu (dropdown menu for actions like bulk actions)
# Component Name

ActionMenu

image

## Key features
- Is a button
- Clicking opens a dropdown menu
- Clicking an option in the menu triggers an `onSelect` event
- The title for the button never automatically changes based on select
- The button may be disabled
- The options may be disabled
- The button will support all major button props, colors, etc
- The button will default to outlined

### PR DESCRIPTION
**Pull request by mikemurray**
Resolves #73
Impact: **minor**  
Type: **feature**

## Component

ActionMenu component based on the Catalyst button and MUI Menu components.

## Screenshots
image

image

## Breaking changes

none

## Testing
1. Open the ActionMenu docs and play around with it

### CODE REVIEW

**Comment by machikoyasuda** [comment]
Remove the padding-top and padding-bottom from MuiListRoot
Screen Shot 2019-08-22 at 2 18 39 PM

The "Actions" text shouldn't jump down so far after you click it.

**Comment by machikoyasuda** [comment]
Disabled text color should be #b3b3b3 `black30`

**Comment by machikoyasuda** [comment]
Just for fun, you could add an `Example` portion of the bottom w/ the ActionMenu next to other buttons, like this:

Screen Shot 2019-08-22 at 2 23 57 PM
(Text Only Button) | (Contained Error Button) | (ActionMenu) - to ensure the heights are all good.

**Comment by machikoyasuda** [comment]
@mikemurray If you rebase (or merge) `master` now, you'll get the benefit of the button line-height correction 😄 📏

**Comment by mikemurray** [comment]
@machikoyasuda merged from master and improved the keyboard navigation

**Comment by machikoyasuda** [comment]
In the spirit of more "real life examples", can you change the Options for one of them to this:

```
const options = [{
  label: "Filter by file"
}, {
  label: "Publish"
}, {
  label: "Make Visible"
}, {
  label: "Make Hidden"
}, {
  label: "Duplicate"
}, {
  label: "Archive"
}];
```

**Pull request merged**
