### PR TITLE
fix(select): update style for select

### LINKED ISSUE #71: Select: Placeholder text should be Caption text size 14px
Screen Shot 2019-08-20 at 11 19 46 AM
14px
vs
Screen Shot 2019-08-20 at 11 20 12 AM
16px

### PR DESCRIPTION
**Pull request by machikoyasuda**
Signed-off-by: Machiko Yasuda <machiko@reactioncommerce.com>

Resolves #71 
Impact: **minor**  
Type: **bugfix**

## Select
- Placeholder text should be 14px, not 16px for both the single and multi Select
- A lot of style/design changes.

## Screenshots
Screen Shot 2019-08-21 at 6 51 56 PM

Screen Shot 2019-08-28 at 4 49 48 PM
Screen Shot 2019-08-28 at 4 49 51 PM

## Breaking changes
This component requires the latest version of `react-select`. Using this component in an app with older versions of `react-select` will have to be updated.

## Testing
1. Design review
1. Code review

### CODE REVIEW

**Comment by machikoyasuda** [comment]
@cassytaylor What should the font size of the options, once they're in the Select input be?

Screen Shot 2019-08-21 at 6 53 17 PM
Screen Shot 2019-08-21 at 6 53 12 PM

What should the color of the hover be? Same as the Action dropdown?

Screen Shot 2019-08-21 at 6 55 44 PM
Screen Shot 2019-08-21 at 6 55 56 PM

And should that container of the values (like Men, Women) be connected to the input?

**Comment by machikoyasuda** [comment]
From Cassy:
- the background color of all selects/text inputs should be black-02..... for now. we've discussed maybe updating it to white later. if it makes sense to
- the placeholder text inside of the select when no options are selected should be black-55 (for web accessibility-appropriate color contrast)
- the select border color should be black-20
- the focus state should be a 2px teal-500 border. if possible, it would be cool to have like a 280ms fade-in/fade-out animation on the focus state, so it's less abrupt when you click into the select!
- we decided we don't actually want a hover state for our inputs and selects (apart from using the pointer cursor for selects, and text cursor for inputs). although a lot of UI kits include these with their form components, it's not standard or required

**Comment by machikoyasuda** [comment]
@cassytaylor @willopez - Ready for a final review now.

**Comment by cassytaylor** [comment]
@willopez I disagree, I like having the various states shown (selected, open menu, etc.) because it makes it easier to inspect those elements - which is handy for Design to make sure our components in Sketch match what's built in Catalyst

**Pull request merged**
